---
title: Blog
timezone: UTC
collections:
  blog:
    title: Blog
    output: true
    permalink: "/:path/"
  blog-authors:
    title: Blog_authors
    output: false
    permalink: "/author/:path/"
  blog-categories:
    title: Blog_categories
    output: true
    permalink: "/category/:path/"
  blog-tags:
    title: Blog_tags
    output: true
    permalink: "/tag/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: blog-categories
  values:
    layout: category
    ar_title: ''
- scope:
    path: ''
    type: blog-tags
  values:
    layout: tag
    ar_title: ''
- scope:
    path: ''
    type: blog-authors
  values:
    work_position: ''
    ar_title: ''
    ar_work_position: ''
    image_asset: ''
    twitter_url: ''
    instagram_url: ''
    facebook_url: ''
    linkedin_url: ''
    youtube_url: ''
- scope:
    path: ''
    type: blog
  values:
    layout: post
    excerpt: ''
    image_asset: ''
    meta_desc: ''
    ar_title: ''
    ar_content_md: ''
    ar_excerpt: ''
    ar_meta_desc: ''
    Blog_categories: ''
    Blog_tags: ''
    Blog_authors: ''
version: Hi9yPAU3TF
title_suffix: Nine Tenths
ar_title_suffix: تسعة أعشار
esso:
  base_url: https://esso.910ths.sa
  client_id: 8
  base_uat_url: https://uat-esso.910ths.sa
  client_uat_id: 24
esso_api:
  base_url: https://esso-api.910ths.sa/api
  base_uat_url: https://uat-esso-api.910ths.sa/api
zendesk_subdomain: 
hotjar_id: 
hotjar_snippet_version: 
google_analytics_ua: 
google_tag_manager_gtm: GTM-PGTQKW3
description: 
ar_description: مدونة تسعة أعشار مدونة تفاعلية موجهة لرواد الأعمال، تطرح عدة مواضيع
  تتمحور حول ريادة الأعمال والعمل الحر، إلى جانب مشاركة قصص النجاح وتناقل الخبرات
  والمعرفة العلمية والتقنية
social:
  twitter: https://twitter.com/910ths
  instagram: https://www.instagram.com/910ths/
  facebook: https://www.facebook.com/910ths
  linkedin: https://www.linkedin.com/company/10429419/
  youtube: https://www.youtube.com/channel/UC-0l5fUO41EnK8MlR1rO9XA
masonry:
  limit: 5
  more_count: 2
  animation_time: 2000
facebook:
  app_id: 314587042375137
  app_secret: 2f1c62181919c413f9970799d9129761
permalink: pretty
markdown: kramdown
exclude:
- gulpfile.js
- package.json
- node_modules
- npm-debug.log
- README.md
- _dev
gems:
- jekyll-multiple-languages-plugin
languages:
- ar
- en
exclude_from_localizations:
- _dev
- build
- fonts
- img
